# coding=utf-8
# Copyright 2018 The Google AI Language Team Authors and The HuggingFace Inc. team.
# Copyright (c) 2018, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
""" SemEval 2016 task 6 utils (dataset loading and evaluation) """


import jsonlines
import logging
import os

from transformers import DataProcessor
from .utils import StanceExample

logger = logging.getLogger(__name__)


class SemEval2016t6Processor(DataProcessor):
    """Processor for the SemEval 2016 task 6 dataset.
    map from label generated by mdl-stance-robustness
    Adapted from https://github.com/google-research/bert/blob/f39e881b169b9d53bea03d2d341b31707a6c052b/run_classifier.py#L207"""

    label_map = {0: 'against',
                 2: 'none',
                 1: 'in favour'}
    language = 'en'
    contexts_dict = {'Atheism': 'Atheism, in the broadest sense, is an absence of belief in the existence of deities',
                     'Climate Change is a Real Concern': 'In common usage, climate change describes global warming; climate change has been strongly affected by climate change denial and misinformation',
                     'Feminist Movement': 'Feminist movement refers to a series of social movements and political campaigns for radical and liberal reforms on women\'s issues created by the inequality between men and women; issues include women\'s liberation, reproductive rights, domestic violence, maternity leave, equal pay, women\'s suffrage, sexual harassment, and sexual violence',
                     'Hillary Clinton': 'Hillary Clinton is an American politician, diplomat, and former lawyer who served as the 67th United States secretary of state from 2009 to 2013 and the Democratic Party nominee against Republican Party\'s Donald Trump in the 2016 presidential election',
                     'Legalization of Abortion': 'Abortion is the termination of a pregnancy by removal or expulsion of an embryo or fetus. Opinions of abortion may be about fetal rights, governmental authority, and women\'s rights'}

    def __init__(self):
        pass

    def get_examples(self, data_dir, split='train'):
      """See base class."""
      examples = []
      lines = jsonlines.jsonlines.open(os.path.join(data_dir, f"semeval2016t6-{split}.json"))

      for (i, line) in enumerate(lines):
        guid = "%s-%s" % (split, i)
        topic = line['premise']
        text = line['hypothesis']
        label = SemEval2016t6Processor.label_map[line['label']]
        context = SemEval2016t6Processor.contexts_dict[topic]
        assert isinstance(topic, str) and isinstance(text, str) and isinstance(label, str) and isinstance(context, str)
        examples.append(StanceExample(guid=guid, topic=topic, text=text, label=label, context=context))
      return examples

    def get_train_examples(self, data_dir):
        return self.get_examples(data_dir, split='train')

    def get_dev_examples(self, data_dir):
        return self.get_examples(data_dir, split='dev')

    def get_test_examples(self, data_dir, ):
        return self.get_examples(data_dir, split='test')

    def get_labels(self):
        """See base class."""
        return ["against", "none", "in favour"]


semeval2016t6_processors = {
    "stance": SemEval2016t6Processor,
}

semeval2016t6_output_modes = {
    "stance": "classification",
}

semeval2016t6_tasks_num_labels = {
    "stance": 3,
}
