# coding=utf-8
# Copyright 2018 The Google AI Language Team Authors and The HuggingFace Inc. team.
# Copyright (c) 2018, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
""" twitter2017 utils (dataset loading and evaluation) """


import csv
import logging
import os

from transformers import DataProcessor
from .utils import StanceExample

logger = logging.getLogger(__name__)


class Twitter2017Processor(DataProcessor):
    """Processor for the twitter2017 dataset.
    map from label generated by TomBERT
    Adapted from https://github.com/google-research/bert/blob/f39e881b169b9d53bea03d2d341b31707a6c052b/run_classifier.py#L207"""

    label_map = {0: 'AGAINST',
                 2: 'FAVOR',
                 1: 'DISCUSS',
                 3: 'UNRELATED'}
    language = 'en'

    def __init__(self):
        pass

    def get_examples(self, data_dir, split='train'):
      """See base class."""
      examples = []
      with open(os.path.join(data_dir, f"twitter2017-{split}.tsv")) as f:
        lines = csv.reader(f, delimiter='\t')
        header = next(lines)
        topic_id = 4
        text_id = 3
        label_id = 1
        n_terms = 5

        for (i, line) in enumerate(lines):
            if len(line) != n_terms:
                print(len(line))
                raise NotImplementedError
            guid = "%s-%s" % (split, i)
            topic = line[topic_id]
            text = line[text_id]
            text = text.replace('$T$', topic)
            label = Twitter2017Processor.label_map[int(line[label_id])]
            assert isinstance(topic, str) and isinstance(text, str) and isinstance(label, str)
            examples.append(StanceExample(guid=guid, topic=topic, text=text, label=label))
      return examples

    def get_train_examples(self, data_dir):
        return self.get_examples(data_dir, split='train')

    def get_dev_examples(self, data_dir):
        return self.get_examples(data_dir, split='dev')

    def get_test_examples(self, data_dir, ):
        return self.get_examples(data_dir, split='test')

    def get_labels(self):
        """See base class."""
        return ["AGAINST", "DISCUSS", "FAVOR", "UNRELATED"]


twitter2017_processors = {
    "stance": Twitter2017Processor,
}

twitter2017_output_modes = {
    "stance": "classification",
}

twitter2017_tasks_num_labels = {
    "stance": 4,
}
